apiVersion: v1
kind: Service
metadata:
  name: taskforce-service
spec:
  selector:
    app: taskforce
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30001
